### ISSUE TITLE
ui5strap.table data binding

### ISSUE THREAD

**Issue by Adanz** [pks5/ui5strap#2]
ui5strap.table how to data binding. have any example? thanks!

**Comment by pks5** [comment]
Assuming you have a model like:

{
      "rows" : [
            {
                    "cols" : [
                              {
                                    "name" : "Column1",
                                    "value" : 123
                              },
                              {
                                    "name" : "Column2",
                                    "value" : 456
                              }
                   ]     
            },
            {
                    "cols" : [
                              {
                                    "value" : "abc"
                              },
                              {
                                    "value" : "cde"
                              }
                   ]     
            }
             
     ]

}

&lt;div data-sap-ui-type="ui5strap.Table" data-body="{MY_MODEL>/rows}">
					&lt;div data-sap-ui-aggregation="head">
						&lt;div data-sap-ui-type="ui5strap.TableRow" data-columns="{MY_MODEL>/rows/0/cols}">
							&lt;div data-sap-ui-type="ui5strap.TableColumn" data-text="{MY_MODEL>name}">&lt;/div>
						&lt;/div>
					&lt;/div>
					&lt;div data-sap-ui-aggregation="body">
						&lt;div data-sap-ui-type="ui5strap.TableRow" data-columns="{MY_MODEL>cols}">
							&lt;div data-sap-ui-type="ui5strap.TableColumn" data-text="{MY_MODEL>value}">&lt;/div>
						&lt;/div>
					&lt;/div>
			&lt;/div>

**Comment by Adanz** [comment]
pass test. correctly. thanks!

ui5strap is great. Does it have like UI5 table control (selected row, filter, sort by column)?

**Comment by pks5** [comment]
Unfortuanely not yet. But we plan to integrate DataTables soon.

**Comment by Adanz** [comment]
0.84 cannot run in IE9, but 0.73 is OK.

And several things are different (Brower  requirements ).

**Comment by pks5** [comment]
Hello,

can you send me a error message or similar, cause i currently have no IE9 here. Not sure why its not working compared to 0.73.

**Comment by Adanz** [comment]
open index.html
Unable to get property 'ui5strap.app.started' of undefined or null reference

and 0.84 remove sap.m.ui ?

**Comment by pks5** [comment]
sap.m and sap.ui.commons is still supported, but you have to include the full openui5 library by yourself. See http://ui5strap.com/examples/net__rozzo__ui5__mtest__app/  

Regarding IE9 Problem: i will check and come back to you soon.

**Comment by pks5** [comment]
Hello, i just committed 0.85, it should fix the IE 9 problem. Please test. Regards

**Comment by Adanz** [comment]
IE9 will test tonight.

but today I found since 0.8 the history is No effect,(Back to the previous page or next page).

0.73 is right.

**Comment by Adanz** [comment]
IE9, when open local index.html or http://ui5strap.com/ui5strap/. An error occurred:

SCRIPT438: Object does not support "debug" property or method
ui5strap, line 233 char 4
